version: '2'
services:

    #####################
    # NGINX
    #####################
    nginx:
        container_name: NODE_nginx
        image         : nginx:stable
        links         :
            - node
        depends_on    :
            - node
        volumes       :
            - ./config/nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - 80:80
            - 443:443

    #####################
    # NODE
    #####################
    node:
        container_name: NODE_apps
        build         : ./build/node/
        volumes       :
            - ./data/process.yml:/SERVER/process.yml
            - /SERVER/www/:/SERVER/